import { Geist, Geist_Mono, Assistant } from "next/font/google";
import "../globals.css";
import { Toaster } from "react-hot-toast";
import LeftSidebar from "../components/Leftsidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const assistant = Assistant({
  variable: "--font-assistant",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "ModaSerena",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${assistant.variable} antialiased bg-white text-gray-900`}
      >
        <div className="flex flex-col lg:flex-row min-h-screen bg-white">
          <div className="bg-gradient-to-b from-pink-50 to-white lg:bg-gradient-to-r lg:from-pink-50 lg:to-white">
            <LeftSidebar />
          </div>
          <div className="flex-1 p-6 lg:p-10 bg-white border-l border-pink-100">
            {children}
          </div>
          <Toaster position="top-center" reverseOrder={false} />
        </div>
      </body>
    </html>
  );
}